# Generated by Django 4.1.1 on 2022-09-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0003_funcionalidade_alter_projeto_funcionalidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='funcionalidades',
        ),
        migrations.DeleteModel(
            name='Funcionalidade',
        ),
    ]
