# Generated by Django 4.1.1 on 2022-09-13 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0004_remove_projeto_funcionalidades_delete_funcionalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomes', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='funcionalidades',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador.funcionalidade'),
        ),
    ]
